In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Employee_Dataset.csv")
data

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
0,EMP1000,IT,Senior Analyst,60,85000,invalid,01/04/2021,5,3,NaN
1,emp_1,IT,Analyst,NaN,55000,10/06/2020,invalid,5,3,True
2,EMP1002,Sales,NaN,28,85000,NaN,2022-03-01,3,4,NaN
3,EMP1003,it,Analyst,45,35000,invalid,01/04/2021,1,3,NaN
4,NaN,IT,mgr,150,85000,NaN,invalid,12,2,True
...,...,...,...,...,...,...,...,...,...,...
995,EMP1995,Finance,NaN,60,55000,2019-05-10,2022-03-01,1,4,yes
996,EMP1996,IT,Analyst,35,250000,invalid,invalid,-2,5,NaN
997,EMP1997,Sales,Senior Analyst,150,250000,2021/07/15,invalid,3,excellent,yes
998,emp_998,Finance,NaN,60,85000,2019-05-10,NaN,12,NaN,True
999,EMP1999,it,Manager,150,₹75000,invalid,2022-03-01,ten,5,yes

## TASK 1

In [3]:
data["joining_date"]=pd.to_datetime(data["joining_date"],errors="coerce")
k=data["joining_date"].isna().sum()
k

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_12184\1947650244.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data["joining_date"]=pd.to_datetime(data["joining_date"],errors="coerce")

np.int64(377)

## TASK 2

In [4]:
data["employee_id"]=data["employee_id"].astype(str)
data["employee_id"]=data["employee_id"].str.strip()
data["employee_id"]=data["employee_id"].str.upper()

In [5]:
data["employee_id"]=data["employee_id"].str.replace(" ","",regex=False)
data["employee_id"]=data["employee_id"].str.replace("_","",regex=False)

In [6]:
data["employee_id"]

0      EMP1000
1         EMP1
2      EMP1002
3      EMP1003
4          NAN
        ...
995    EMP1995
996    EMP1996
997    EMP1997
998     EMP998
999    EMP1999
Name: employee_id, Length: 1000, dtype: object

In [7]:
dup=data["employee_id"].duplicated().sum()
dup

np.int64(503)

In [8]:
data

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
0,EMP1000,IT,Senior Analyst,60,85000,NaT,01/04/2021,5,3,NaN
1,EMP1,IT,Analyst,NaN,55000,2020-10-06,invalid,5,3,True
2,EMP1002,Sales,NaN,28,85000,NaT,2022-03-01,3,4,NaN
3,EMP1003,it,Analyst,45,35000,NaT,01/04/2021,1,3,NaN
4,NAN,IT,mgr,150,85000,NaT,invalid,12,2,True
...,...,...,...,...,...,...,...,...,...,...
995,EMP1995,Finance,NaN,60,55000,2019-05-10,2022-03-01,1,4,yes
996,EMP1996,IT,Analyst,35,250000,NaT,invalid,-2,5,NaN
997,EMP1997,Sales,Senior Analyst,150,250000,2021-07-15,invalid,3,excellent,yes
998,EMP998,Finance,NaN,60,85000,2019-05-10,NaN,12,NaN,True
999,EMP1999,it,Manager,150,₹75000,NaT,2022-03-01,ten,5,yes

## TASK 3

In [9]:
data["department"]=data["department"].str.strip()
data["department"]=data["department"].str.upper()

In [10]:
data["department"].tail(100)

900         IT
901         HR
902         IT
903      SALES
904         IT
        ...
995    FINANCE
996         IT
997      SALES
998    FINANCE
999         IT
Name: department, Length: 100, dtype: object

In [11]:
data["salary"] = data["salary"].str.replace("₹", "", regex=False)
data["salary"] = data["salary"].str.replace(",", "", regex=False)
data["salary"] = pd.to_numeric(data["salary"], errors="coerce")

In [12]:
data["salary"]

0       85000.0
1       55000.0
2       85000.0
3       35000.0
4       85000.0
         ...
995     55000.0
996    250000.0
997    250000.0
998     85000.0
999     75000.0
Name: salary, Length: 1000, dtype: float64

In [13]:
data

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
0,EMP1000,IT,Senior Analyst,60,85000.0,NaT,01/04/2021,5,3,NaN
1,EMP1,IT,Analyst,NaN,55000.0,2020-10-06,invalid,5,3,True
2,EMP1002,SALES,NaN,28,85000.0,NaT,2022-03-01,3,4,NaN
3,EMP1003,IT,Analyst,45,35000.0,NaT,01/04/2021,1,3,NaN
4,NAN,IT,mgr,150,85000.0,NaT,invalid,12,2,True
...,...,...,...,...,...,...,...,...,...,...
995,EMP1995,FINANCE,NaN,60,55000.0,2019-05-10,2022-03-01,1,4,yes
996,EMP1996,IT,Analyst,35,250000.0,NaT,invalid,-2,5,NaN
997,EMP1997,SALES,Senior Analyst,150,250000.0,2021-07-15,invalid,3,excellent,yes
998,EMP998,FINANCE,NaN,60,85000.0,2019-05-10,NaN,12,NaN,True
999,EMP1999,IT,Manager,150,75000.0,NaT,2022-03-01,ten,5,yes

In [14]:
avg_sal=data.groupby("department")["salary"].mean()
avg_sal

department
FINANCE    107397.959184
HR         110117.647059
IT         103373.205742
SALES      110842.696629
Name: salary, dtype: float64

## TASK 4

In [15]:
data["age"]=pd.to_numeric(data["age"], errors="coerce")
data[(data["salary"].notna()) & (data["age"].isna())]

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
1,EMP1,IT,Analyst,NaN,55000.0,2020-10-06,invalid,5,3,True
5,NAN,IT,mgr,NaN,75000.0,2019-05-10,invalid,8,3,no
30,EMP1030,HR,Manager,NaN,85000.0,2019-05-10,invalid,3,3,True
31,NAN,HR,Analyst,NaN,55000.0,2020-10-06,2022-03-01,1,4,NaN
38,EMP38,IT,Manager,NaN,35000.0,2021-07-15,2022-03-01,1,poor,True
...,...,...,...,...,...,...,...,...,...,...
959,NAN,HR,NaN,NaN,120000.0,2020-10-06,invalid,8,3,NaN
974,EMP974,NaN,mgr,NaN,85000.0,2021-07-15,01/04/2021,3,4,False
976,EMP1976,HR,Analyst,NaN,250000.0,2019-05-10,NaN,1,poor,False
982,NAN,HR,NaN,NaN,55000.0,2020-10-06,NaN,5,NaN,NaN
991,NAN,IT,Analyst,NaN,120000.0,2020-10-06,2022-03-01,-2,4,yes

## TASK 6

In [16]:
data["performance_rating"]=pd.to_numeric(data["performance_rating"], errors="coerce")

In [17]:
data.groupby("designation")["performance_rating"].median()

designation
ANALYST           3.0
Analyst           3.0
Manager           3.0
Senior Analyst    3.0
mgr               3.0
Name: performance_rating, dtype: float64

## TASK 7

In [18]:
data["last_promotion_date"]=pd.to_datetime(data["last_promotion_date"],errors="coerce")
data[data["last_promotion_date"]<data["joining_date"]]

#I have error here remember

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
24,EMP1024,FINANCE,mgr,35.0,85000.0,2021-07-15,2021-01-04,8,3.0,True
40,EMP40,NaN,NaN,60.0,85000.0,2021-07-15,2021-01-04,12,5.0,True
44,EMP44,SALES,mgr,45.0,75000.0,2021-07-15,2021-01-04,8,2.0,True
47,NAN,FINANCE,Analyst,NaN,250000.0,2021-07-15,2021-01-04,3,NaN,True
71,EMP71,SALES,Manager,60.0,250000.0,2021-07-15,2021-01-04,12,NaN,False
82,EMP82,SALES,Senior Analyst,150.0,NaN,2021-07-15,2021-01-04,-2,1.0,yes
85,NAN,SALES,NaN,60.0,55000.0,2021-07-15,2021-01-04,NaN,2.0,yes
124,NAN,SALES,Analyst,NaN,250000.0,2021-07-15,2021-01-04,1,5.0,no
138,EMP138,FINANCE,mgr,45.0,250000.0,2021-07-15,2021-01-04,NaN,3.0,False
169,EMP169,IT,mgr,60.0,120000.0,2021-07-15,2021-01-04,NaN,2.0,NaN
187,NAN,NaN,ANALYST,150.0,250000.0,2021-07-15,2021-01-04,12,4.0,no
191,EMP1191,SALES,mgr,NaN,NaN,2021-07-15,2021-01-04,NaN,NaN,yes
200,NAN,SALES,mgr,22.0,35000.0,2021-07-15,2021-01-04,NaN,2.0,no
243,NAN,SALES,mgr,NaN,NaN,2021-07-15,2021-01-04,5,NaN,NaN
247,NAN,HR,Senior Analyst,-5.0,250000.0,2021-07-15,2021-01-04,-2,3.0,True
269,NAN,HR,mgr,NaN,NaN,2021-07-15,2021-01-04,ten,NaN,no
275,NAN,NaN,Analyst,45.0,NaN,2021-07-15,2021-01-04,1,5.0,False
293,EMP1293,HR,NaN,60.0,NaN,2021-07-15,2021-01-04,8,NaN,NaN
331,EMP331,FINANCE,ANALYST,150.0,NaN,2021-07-15,2021-01-04,8,2.0,yes
360,EMP360,HR,NaN,150.0,85000.0,2021-07-15,2021-01-04,3,1.0,False
371,NAN,SALES,Manager,60.0,250000.0,2021-07-15,2021-01-04,3,3.0,False
379,EMP1379,FINANCE,Senior Analyst,-5.0,NaN,2021-07-15,2021-01-04,8,NaN,yes
390,EMP390,NaN,mgr,60.0,35000.0,2021-07-15,2021-01-04,8,NaN,no
416,NAN,HR,mgr,45.0,120000.0,2021-07-15,2021-01-04,1,NaN,False
423,NAN,HR,NaN,NaN,NaN,2021-07-15,2021-01-04,12,2.0,False
482,EMP482,FINANCE,NaN,22.0,85000.0,2021-07-15,2021-01-04,5,NaN,False
499,EMP1499,SALES,ANALYST,NaN,55000.0,2021-07-15,2021-01-04,NaN,NaN,NaN
508,NAN,HR,Analyst,60.0,85000.0,2021-07-15,2021-01-04,8,1.0,True
513,NAN,IT,mgr,45.0,85000.0,2021-07-15,2021-01-04,12,4.0,NaN
538,EMP1538,NaN,mgr,60.0,NaN,2021-07-15,2021-01-04,1,3.0,True
548,NAN,IT,Manager,60.0,35000.0,2021-07-15,2021-01-04,NaN,1.0,no
556,NAN,HR,Senior Analyst,NaN,35000.0,2021-07-15,2021-01-04,8,3.0,NaN
576,NAN,IT,Analyst,NaN,250000.0,2021-07-15,2021-01-04,1,2.0,NaN
578,NAN,HR,ANALYST,45.0,NaN,2021-07-15,2021-01-04,3,5.0,yes
590,NAN,FINANCE,mgr,NaN,55000.0,2021-07-15,2021-01-04,8,2.0,True
607,NAN,SALES,Analyst,-5.0,NaN,2021-07-15,2021-01-04,NaN,4.0,yes
651,EMP651,IT,Senior Analyst,NaN,NaN,2021-07-15,2021-01-04,8,NaN,True
663,EMP663,IT,Senior Analyst,28.0,NaN,2021-07-15,2021-01-04,3,NaN,NaN
697,EMP697,SALES,Senior Analyst,35.0,250000.0,2021-07-15,2021-01-04,12,NaN,True
722,EMP1722,IT,Manager,22.0,NaN,2021-07-15,2021-01-04,12,4.0,no
739,EMP1739,SALES,NaN,45.0,75000.0,2021-07-15,2021-01-04,NaN,NaN,yes
752,NAN,IT,ANALYST,60.0,250000.0,2021-07-15,2021-01-04,3,1.0,True
772,NAN,HR,mgr,60.0,55000.0,2021-07-15,2021-01-04,1,4.0,True
781,NAN,HR,Manager,45.0,85000.0,2021-07-15,2021-01-04,5,4.0,False
833,NAN,FINANCE,ANALYST,NaN,35000.0,2021-07-15,2021-01-04,-2,3.0,NaN
838,EMP838,NaN,ANALYST,60.0,35000.0,2021-07-15,2021-01-04,ten,NaN,True
851,EMP1851,FINANCE,Analyst,NaN,NaN,2021-07-15,2021-01-04,12,4.0,True
861,EMP861,NaN,NaN,60.0,NaN,2021-07-15,2021-01-04,12,1.0,NaN
877,NAN,SALES,Analyst,NaN,120000.0,2021-07-15,2021-01-04,1,1.0,True
974,EMP974,NaN,mgr,NaN,85000.0,2021-07-15,2021-01-04,3,4.0,False

In [19]:
data["last_promotion_date"].tail(100)

900          NaT
901   2021-01-04
902          NaT
903          NaT
904   2021-01-04
         ...
995          NaT
996          NaT
997          NaT
998          NaT
999          NaT
Name: last_promotion_date, Length: 100, dtype: datetime64[ns]

## TASK 8

In [20]:
data["experience_years"]=pd.to_numeric(data["experience_years"], errors="coerce")
data.loc[data["experience_years"] < 0, "experience_years"] = np.nan
data["experience_years"]

0       5.0
1       5.0
2       3.0
3       1.0
4      12.0
       ...
995     1.0
996     NaN
997     3.0
998    12.0
999     NaN
Name: experience_years, Length: 1000, dtype: float64

In [21]:
data.loc[data["experience_years"]>data["age"], "experience_years"]

10      8.0
17      3.0
43      1.0
49      5.0
56      8.0
       ...
945     3.0
949     5.0
965    12.0
990    12.0
994    12.0
Name: experience_years, Length: 90, dtype: float64

## TASK 9

In [22]:
data

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active
0,EMP1000,IT,Senior Analyst,60.0,85000.0,NaT,2021-01-04,5.0,3.0,NaN
1,EMP1,IT,Analyst,NaN,55000.0,2020-10-06,NaT,5.0,3.0,True
2,EMP1002,SALES,NaN,28.0,85000.0,NaT,NaT,3.0,4.0,NaN
3,EMP1003,IT,Analyst,45.0,35000.0,NaT,2021-01-04,1.0,3.0,NaN
4,NAN,IT,mgr,150.0,85000.0,NaT,NaT,12.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...
995,EMP1995,FINANCE,NaN,60.0,55000.0,2019-05-10,NaT,1.0,4.0,yes
996,EMP1996,IT,Analyst,35.0,250000.0,NaT,NaT,NaN,5.0,NaN
997,EMP1997,SALES,Senior Analyst,150.0,250000.0,2021-07-15,NaT,3.0,NaN,yes
998,EMP998,FINANCE,NaN,60.0,85000.0,2019-05-10,NaT,12.0,NaN,True
999,EMP1999,IT,Manager,150.0,75000.0,NaT,NaT,NaN,5.0,yes

In [23]:
data["designation"]=data["designation"].str.strip()
data["designation"]=data["designation"].str.upper()

In [24]:
data["designation"] = data["designation"].str.replace(".", "", regex=False)
data["designation"] = data["designation"].str.replace("/", "", regex=False)

In [25]:
mapping = {
    "MGR": "MANAGER",
    "SR MANAGER": "MANAGER",
    "SENIOR MANAGER": "MANAGER",
    "SOFTWARE ENG": "SOFTWARE ENGINEER",
    "SW ENGINEER": "SOFTWARE ENGINEER",
    "S/W ENGINEER": "SOFTWARE ENGINEER",
    "DEV": "DEVELOPER",
    "PROGRAMMER": "DEVELOPER"
}

data["designation"] = data["designation"].replace(mapping)

In [26]:
mapp={"yes":"TRUE","no":"FALSE","true":"TRUE","false":"FALSE"}
data["is_active"]=data["is_active"].str.strip().str.lower().replace(mapp)

In [27]:
data["is_active"]

0       NaN
1      TRUE
2       NaN
3       NaN
4      TRUE
       ...
995    TRUE
996     NaN
997    TRUE
998    TRUE
999    TRUE
Name: is_active, Length: 1000, dtype: object

In [28]:
active=data["is_active"].value_counts()
active

is_active
TRUE     422
FALSE    374
Name: count, dtype: int64

In [29]:
data.groupby("department")["is_active"].apply(lambda x: x[x == "TRUE"].count())

department
FINANCE     58
HR          99
IT         113
SALES       96
Name: is_active, dtype: int64

## TASK 10

In [30]:

data["is_active"] = data["is_active"].map({
    "TRUE": True,
    "FALSE": False,
    "YES": True,
    "NO": False,
    "Y": True,
    "N": False,
    "1": True,
    "0": False,
    "ACTIVE": True,
    "INACTIVE": False
})

In [33]:
data["is_active"].tail(100)

900    False
901      NaN
902      NaN
903    False
904    False
       ...
995     True
996      NaN
997     True
998     True
999     True
Name: is_active, Length: 100, dtype: object

In [35]:
data["is_active"] = data["is_active"].astype("boolean")

In [36]:
data["is_active"].dtype

BooleanDtype

## TASK 11

In [37]:
data["joining_date"] = pd.to_datetime(
    data["joining_date"],
    dayfirst=True,
    errors="coerce"
)

In [38]:
today = pd.Timestamp.today()

data["tenure_years"] = (today - data["joining_date"]).dt.days / 365

In [39]:
data["tenure_years"]

0           NaN
1      5.350685
2           NaN
3           NaN
4           NaN
         ...
995    6.761644
996         NaN
997    4.578082
998    6.761644
999         NaN
Name: tenure_years, Length: 1000, dtype: float64

## TASK 12

In [41]:
dept_salary_issue = data.groupby("department")["salary"].mean() * 100
dept_salary_issue

department
FINANCE    1.073980e+07
HR         1.101176e+07
IT         1.033732e+07
SALES      1.108427e+07
Name: salary, dtype: float64

In [42]:
problem_dept = dept_salary_issue[dept_salary_issue > 25]
problem_dept

department
FINANCE    1.073980e+07
HR         1.101176e+07
IT         1.033732e+07
SALES      1.108427e+07
Name: salary, dtype: float64

## TASK 13

In [43]:
median_salary = data["salary"].median()
median_salary

85000.0

In [45]:
data["underpaid_high_performer"] = (
    (data["performance_rating"] >= 4) &
    (data["salary"] < median_salary)
)
data[data["underpaid_high_performer"]]

,employee_id,department,designation,age,salary,joining_date,last_promotion_date,experience_years,performance_rating,is_active,tenure_years,underpaid_high_performer
21,NAN,HR,SENIOR ANALYST,45.0,55000.0,NaT,NaT,NaN,4.0,True,NaN,True
26,NAN,FINANCE,SENIOR ANALYST,28.0,75000.0,2019-05-10,NaT,8.0,5.0,True,6.761644,True
29,NAN,FINANCE,MANAGER,28.0,55000.0,2019-05-10,NaT,NaN,4.0,True,6.761644,True
31,NAN,HR,ANALYST,NaN,55000.0,2020-10-06,NaT,1.0,4.0,<NA>,5.350685,True
60,NAN,SALES,SENIOR ANALYST,45.0,75000.0,NaT,NaT,3.0,4.0,True,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...
946,NAN,IT,SENIOR ANALYST,45.0,35000.0,2019-05-10,NaT,8.0,5.0,<NA>,6.761644,True
964,NAN,IT,ANALYST,45.0,55000.0,2021-07-15,NaT,NaN,4.0,False,4.578082,True
988,EMP1988,FINANCE,ANALYST,35.0,55000.0,NaT,2021-01-04,NaN,5.0,<NA>,NaN,True
995,EMP1995,FINANCE,NaN,60.0,55000.0,2019-05-10,NaT,1.0,4.0,True,6.761644,True
999,EMP1999,IT,MANAGER,150.0,75000.0,NaT,NaT,NaN,5.0,True,NaN,True

## TASK 14

In [46]:
data["experience_years"] = pd.to_numeric(data["experience_years"], errors="coerce")

In [47]:
no_promo_5yrs = data[
    (data["last_promotion_date"].isna()) &
    (data["experience_years"] > 5)
]

In [49]:
data["missing_promotion_record"] = (
    (data["last_promotion_date"].isna()) &
    (data["experience_years"] > 5)
)
data["missing_promotion_record"]

0      False
1      False
2      False
3      False
4       True
       ...
995    False
996    False
997    False
998     True
999    False
Name: missing_promotion_record, Length: 1000, dtype: bool

## TASK 15