In [74]:
import pandas as pd
import numpy as np

In [75]:
df=pd.read_csv("Dataset_1.csv")
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,yes
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,yes
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,True

## TASK 1 --> identify all rows where order_amount is nonnumeric

In [76]:

non_numeric_rows = df[(df['order_amount'].isna()) & ((df['is_delivered']=='yes')|(df['is_delivered']=='True'))]
non_numeric_rows

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
14,ORD1014,CUST14,25.0,NaN,2023/03/10,upi,DELHI,5,yes
17,NaN,NaN,-3.0,NaN,15/02/2023,upi,Hyderabad,NaN,True
29,NaN,user_29,NaN,NaN,NaN,Debit Card,DELHI,7,True
38,NaN,CUST38,35.0,NaN,15/02/2023,CARD,NaN,1,True
...,...,...,...,...,...,...,...,...,...
970,ORD1970,NaN,18.0,NaN,NaN,Cash,Hyderabad,7,yes
982,NaN,CUST982,25.0,NaN,15/02/2023,NaN,Bangalore,2,yes
987,NaN,CUST987,50.0,NaN,2023/03/10,NaN,Bangalore,NaN,yes
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,yes
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,True

In [77]:
non_numeric=pd.to_numeric(df['order_amount'],errors='coerce')
non_numeric
df.head(50)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,yes
5,NaN,NaN,NaN,1200,2023-01-15,CARD,mumbai,1,False
6,ORD1006,CUST6,-3.0,NaN,NaN,upi,Bangalore,5,no
7,ORD1007,NaN,120.0,NaN,2023-01-15,CARD,NaN,5,no
8,ORD1008,user_8,18.0,NaN,2023/03/10,Debit Card,NaN,7,False
9,NaN,user_9,NaN,NaN,2023/03/10,UPI,Delhi,-1,no
10,NaN,NaN,65.0,₹999,2023-01-15,Credit Card,Bangalore,7,False
11,NaN,CUST11,18.0,3500.75,NaN,Cash,Mumbai,-1,False
12,ORD1012,NaN,65.0,₹999,invalid,Credit Card,Delhi,7,False
13,NaN,CUST13,NaN,NaN,invalid,Cash,Mumbai,7,False
14,ORD1014,CUST14,25.0,NaN,2023/03/10,upi,DELHI,5,yes
15,NaN,CUST15,NaN,499.99,2023-01-15,Credit Card,Hyderabad,2,NaN
16,NaN,NaN,50.0,₹999,15/02/2023,CARD,Delhi,NaN,NaN
17,NaN,NaN,-3.0,NaN,15/02/2023,upi,Hyderabad,NaN,True
18,NaN,user_18,18.0,250.5,2023/03/10,Cash,Hyderabad,5,yes
19,NaN,user_19,NaN,250.5,NaN,Debit Card,Mumbai,2,NaN
20,NaN,NaN,18.0,1200,invalid,NaN,Delhi,5,NaN
21,NaN,NaN,25.0,499.99,NaN,Credit Card,Mumbai,NaN,yes
22,NaN,NaN,35.0,3500.75,2023-01-15,Debit Card,Mumbai,NaN,NaN
23,NaN,NaN,35.0,3500.75,NaN,NaN,NaN,1,no
24,ORD1024,CUST24,NaN,₹999,invalid,Credit Card,DELHI,1,yes
25,NaN,NaN,35.0,3500.75,2023/03/10,Cash,DELHI,1,True
26,NaN,user_26,25.0,NaN,2023/03/10,Debit Card,Hyderabad,7,no
27,NaN,NaN,25.0,₹999,2023-01-15,NaN,NaN,NaN,True
28,ORD1028,CUST28,NaN,₹999,NaN,Cash,NaN,NaN,NaN
29,NaN,user_29,NaN,NaN,NaN,Debit Card,DELHI,7,True
30,ORD1030,user_30,65.0,3500.75,15/02/2023,CARD,DELHI,NaN,no
31,NaN,user_31,18.0,NaN,2023/03/10,CARD,mumbai,three,False
32,ORD1032,NaN,25.0,NaN,2023-01-15,CARD,mumbai,2,NaN
33,ORD1033,user_33,120.0,499.99,15/02/2023,upi,Bangalore,NaN,yes
34,ORD1034,NaN,120.0,3500.75,2023/03/10,Debit Card,Hyderabad,7,True
35,NaN,user_35,50.0,499.99,NaN,Cash,DELHI,-1,yes
36,NaN,CUST36,50.0,499.99,2023/03/10,Credit Card,Bangalore,7,NaN
37,NaN,NaN,NaN,3500.75,15/02/2023,CARD,mumbai,7,NaN
38,NaN,CUST38,35.0,NaN,15/02/2023,CARD,NaN,1,True
39,NaN,NaN,65.0,NaN,invalid,Debit Card,Mumbai,three,True
40,NaN,NaN,35.0,NaN,15/02/2023,UPI,Hyderabad,1,True
41,NaN,NaN,18.0,3500.75,invalid,UPI,mumbai,three,yes
42,NaN,user_42,18.0,NaN,invalid,NaN,Hyderabad,NaN,True
43,ORD1043,NaN,50.0,499.99,15/02/2023,CARD,Mumbai,7,yes
44,ORD1044,NaN,NaN,3500.75,15/02/2023,upi,mumbai,three,yes
45,ORD1045,NaN,50.0,₹999,NaN,Debit Card,Delhi,NaN,no
46,ORD1046,NaN,35.0,₹999,15/02/2023,upi,Delhi,7,False
47,NaN,user_47,25.0,NaN,2023/03/10,Cash,Mumbai,-1,NaN
48,NaN,NaN,50.0,₹999,2023-01-15,Credit Card,Delhi,1,yes
49,ORD1049,CUST49,120.0,3500.75,15/02/2023,NaN,Hyderabad,-1,False

In [78]:
rep={'yes':'True','True':'True','No':'False','False':'False'}
df['is_delivered']=df['is_delivered'].replace(rep)
df['is_delivered']

0       True
1       True
2       True
3      False
4       True
       ...
995     True
996     True
997      NaN
998    False
999     True
Name: is_delivered, Length: 1000, dtype: object

In [6]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,True
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,True
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,True
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,True
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,True

In [7]:
for i in df:
    if(df['order_amount'].isnull()) and ((df['is_delivered']=='True')):
        df['is_delivered']=df['is_delivered'].replace({'True':'False','False':'False'})
df

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

## TASK 2 -->Convert order_date to datetime and find orders where delivery days is negative after valid date conversion

In [79]:
df['order_date']=pd.to_datetime(df['order_date'],errors='coerce',format='%Y-%m-%d',dayfirst=True)
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,NaT,Debit Card,NaN,5,True
2,ORD1002,CUST2,35.0,NaN,NaT,NaN,Mumbai,7,True
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,True
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,NaT,upi,Mumbai,1,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,True
997,NaN,user_997,50.0,NaN,NaT,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,NaN,NaT,Debit Card,NaN,-1,True

In [80]:
rep1={'Three':3,'three':3}
df['delivery_days']=df['delivery_days'].replace(rep1)
df['delivery_days']=pd.to_numeric(df['delivery_days'],errors='coerce')
df['delivery_days']

0      5.0
1      5.0
2      7.0
3      3.0
4      3.0
      ...
995    1.0
996    2.0
997    1.0
998    2.0
999   -1.0
Name: delivery_days, Length: 1000, dtype: float64

In [81]:
import numpy as np
df['delivery_days']=pd.to_numeric(df['delivery_days'], errors='coerce')
df.loc[df['delivery_days']<0, 'delivery_days'] = np.nan
df['delivery_days']

0      5.0
1      5.0
2      7.0
3      3.0
4      3.0
      ...
995    1.0
996    2.0
997    1.0
998    2.0
999    NaN
Name: delivery_days, Length: 1000, dtype: float64

## TASK 3 ---> Standardize payment mode and calulate the percentage share of each mode per city.

In [82]:
payment=pd.value_counts(df['payment_mode'])
payment

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_21396\3312840693.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  payment=pd.value_counts(df['payment_mode'])

payment_mode
Cash           158
UPI            157
CARD           151
Debit Card     141
upi            135
Credit Card    123
Name: count, dtype: int64

In [83]:
cityy=pd.value_counts(df['city'])
cityy

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_21396\627616947.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  cityy=pd.value_counts(df['city'])

city
Delhi        161
Bangalore    151
Mumbai       145
DELHI        141
Hyderabad    141
mumbai       119
Name: count, dtype: int64

In [27]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5.0,True
1,ORD1001,NaN,18.0,1200,NaT,Debit Card,NaN,5.0,True
2,ORD1002,CUST2,35.0,NaN,NaT,NaN,Mumbai,7.0,True
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,3.0,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,3.0,True
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,NaT,upi,Mumbai,1.0,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2.0,True
997,NaN,user_997,50.0,NaN,NaT,Cash,Delhi,1.0,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2.0,False
999,NaN,user_999,120.0,NaN,NaT,Debit Card,NaN,NaN,True

In [84]:
df['payment_mode']=(df['payment_mode']).str.strip().str.lower()
df['payment_mode']

0       debit card
1       debit card
2              NaN
3             cash
4             card
          ...
995            upi
996    credit card
997           cash
998            NaN
999     debit card
Name: payment_mode, Length: 1000, dtype: object

In [85]:
df['city']=(df['city']).str.strip().str.lower()

In [86]:
# df['percentage']=(df.groupby('city')['payment_mode'].value_counts(normalize=True)*100)

share = df.groupby(['city', 'payment_mode']).size()
percentage = share / share.groupby(level=0).sum() * 100

In [87]:
percentage_df=pd.DataFrame(percentage,columns=['percentage']).reset_index()
percentage_df

         city payment_mode  percentage
0   bangalore         card   19.531250
1   bangalore         cash   17.187500
2   bangalore  credit card   11.718750
3   bangalore   debit card   18.750000
4   bangalore          upi   32.812500
5       delhi         card   17.582418
6       delhi         cash   16.849817
7       delhi  credit card   15.018315
8       delhi   debit card   17.948718
9       delhi          upi   32.600733
10  hyderabad         card   19.658120
11  hyderabad         cash   17.094017
12  hyderabad  credit card   15.384615
13  hyderabad   debit card   17.094017
14  hyderabad          upi   30.769231
15     mumbai         card   13.839286
16     mumbai         cash   19.642857
17     mumbai  credit card   14.285714
18     mumbai   debit card   16.071429
19     mumbai          upi   36.160714

## TASK 4 -->Detect customers whose  customer_age is invalid but have order amounts above the median

In [88]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,debit card,NaN,5.0,True
1,ORD1001,NaN,18.0,1200,NaT,debit card,NaN,5.0,True
2,ORD1002,CUST2,35.0,NaN,NaT,NaN,mumbai,7.0,True
3,ORD1003,user_3,35.0,1200,2023-01-15,cash,NaN,3.0,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,NaN,3.0,True
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,NaT,upi,mumbai,1.0,True
996,NaN,CUST996,18.0,NaN,2023-01-15,credit card,hyderabad,2.0,True
997,NaN,user_997,50.0,NaN,NaT,cash,delhi,1.0,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,mumbai,2.0,False
999,NaN,user_999,120.0,NaN,NaT,debit card,NaN,NaN,True

In [89]:
df['customer_age']=pd.to_numeric(df['customer_age'],errors='coerce')
df['customer_age']

0        NaN
1       18.0
2       35.0
3       35.0
4       -3.0
       ...
995     -3.0
996     18.0
997     50.0
998     65.0
999    120.0
Name: customer_age, Length: 1000, dtype: float64

In [90]:
df[((df['customer_age']<0) | (df['customer_age'].isna())) ]

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,debit card,NaN,5.0,True
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,NaN,3.0,True
5,NaN,NaN,NaN,1200,2023-01-15,card,mumbai,1.0,False
6,ORD1006,CUST6,-3.0,NaN,NaT,upi,bangalore,5.0,no
9,NaN,user_9,NaN,NaN,NaT,upi,delhi,NaN,no
...,...,...,...,...,...,...,...,...,...
989,ORD1989,NaN,NaN,1200,2023-01-15,upi,mumbai,3.0,no
991,NaN,NaN,-3.0,3500.75,NaT,card,hyderabad,1.0,True
992,NaN,CUST992,NaN,NaN,2023-01-15,card,NaN,3.0,False
994,NaN,NaN,NaN,250.5,NaT,debit card,bangalore,3.0,no
995,NaN,user_995,-3.0,3500.75,NaT,upi,mumbai,1.0,True

In [97]:
df['order_amount']=pd.to_numeric(df['order_amount'],errors='coerce')
med=df['order_amount'].median()
data=df[(df['customer_age'].isna()) & (df ['order_amount']>med)]
data

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
5,NaN,NaN,NaN,1200.00,2023-01-15,card,mumbai,1.0,False
37,NaN,NaN,NaN,3500.75,NaT,card,mumbai,7.0,NaN
44,ORD1044,NaN,NaN,3500.75,NaT,upi,mumbai,3.0,True
75,NaN,CUST75,NaN,1200.00,NaT,upi,delhi,1.0,False
76,NaN,NaN,NaN,3500.75,NaT,NaN,hyderabad,NaN,True
...,...,...,...,...,...,...,...,...,...
895,ORD1895,user_895,NaN,1200.00,NaT,debit card,bangalore,NaN,True
902,NaN,user_902,NaN,1200.00,NaT,upi,hyderabad,3.0,True
924,NaN,NaN,NaN,3500.75,2023-01-15,card,bangalore,NaN,True
930,ORD1930,NaN,NaN,1200.00,NaT,NaN,delhi,1.0,True
989,ORD1989,NaN,NaN,1200.00,2023-01-15,upi,mumbai,3.0,no

## TASK 5 --> Find duplicate customer_ids where the same customer placed orders in multiple cities.

In [108]:
## TASK 5 --> Find duplicate customer_ids where the same customer placed orders in multiple cities.
unique_city=df.groupby('customer_id')['city'].nunique()
cust_order=unique_city[unique_city>=1].reset_index()
cust_order

    customer_id  city
0       CUST108     1
1        CUST11     1
2       CUST111     1
3       CUST117     1
4       CUST119     1
..          ...   ...
408    user_959     1
409     user_97     1
410    user_977     1
411    user_995     1
412    user_997     1

[413 rows x 2 columns]

## TASK 6 ---> Create a flag for orders where delivery_days is missing but is_delivered is True.

In [109]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.50,2023-01-15,debit card,NaN,5.0,True
1,ORD1001,NaN,18.0,1200.00,NaT,debit card,NaN,5.0,True
2,ORD1002,CUST2,35.0,NaN,NaT,NaN,mumbai,7.0,True
3,ORD1003,user_3,35.0,1200.00,2023-01-15,cash,NaN,3.0,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,NaN,3.0,True
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,NaT,upi,mumbai,1.0,True
996,NaN,CUST996,18.0,NaN,2023-01-15,credit card,hyderabad,2.0,True
997,NaN,user_997,50.0,NaN,NaT,cash,delhi,1.0,NaN
998,ORD1998,NaN,65.0,1200.00,2023-01-15,NaN,mumbai,2.0,False
999,NaN,user_999,120.0,NaN,NaT,debit card,NaN,NaN,True

In [131]:
result = df[(df['delivery_days'].isna()) & (df['is_delivered'].isin(['True', 'yes']))]
result
# df[result].value_counts()

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
17,NaN,NaN,-3.0,NaN,NaT,upi,hyderabad,NaN,True
21,NaN,NaN,25.0,499.99,NaT,credit card,mumbai,NaN,True
27,NaN,NaN,25.0,NaN,2023-01-15,NaN,NaN,NaN,True
33,ORD1033,user_33,120.0,499.99,NaT,upi,bangalore,NaN,True
35,NaN,user_35,50.0,499.99,NaT,cash,delhi,NaN,True
...,...,...,...,...,...,...,...,...,...
967,NaN,NaN,65.0,NaN,NaT,NaN,mumbai,NaN,True
979,NaN,NaN,18.0,1200.00,NaT,NaN,hyderabad,NaN,True
980,NaN,CUST980,NaN,250.50,NaT,cash,bangalore,NaN,True
987,NaN,CUST987,50.0,NaN,NaT,NaN,bangalore,NaN,True
999,NaN,user_999,120.0,NaN,NaT,debit card,NaN,NaN,True

## TASK-7

In [137]:
# compute the average order amount per each payment mode excluding invalid amounts

k=df.groupby('payment_mode')['order_amount'].mean()
gg=k.reset_index(name='average_order')
gg

  payment_mode  average_order
0         card    1553.016237
1         cash    1414.393708
2  credit card    1243.262656
3   debit card    1432.739318
4          upi    1349.349091

In [150]:
# identify cities with missing order dates
missing_order_dates = df[df['order_date'].isna()]['city'].unique()
missing_order_dates [ missing_order_dates > 30]

TypeError: '>' not supported between instances of 'str' and 'int'