In [15]:
import pandas as pd
import numpy as np

In [18]:
dataset=pd.read_csv('dataset.csv')

In [ ]:
data={'Name':['Alice','Bob','Charlie'],
'Age':[25,30,35],
'City':['New York','Los Angeles','Chicago']}

In [5]:
arra_4d=[[[[1,2],[3,4]],[[5,6],[7,8]]], 
         [[[9,10],[11,12]],[[13,14],[15,16]]]]

## PANDAS

In [9]:
tabluar=pd.DataFrame(arra_4d,columns=['Col1','Col2'],index=['Row1','Row2'])
tabluar

                     Col1                  Col2
Row1     [[1, 2], [3, 4]]      [[5, 6], [7, 8]]
Row2  [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [10]:
jso=tabluar.to_json()
jso

'{"Col1":{"Row1":[[1,2],[3,4]],"Row2":[[9,10],[11,12]]},"Col2":{"Row1":[[5,6],[7,8]],"Row2":[[13,14],[15,16]]}}'

In [14]:
tabluar=tabluar.rename(columns={'Col1':'Column_1','Col2':'Column_2'})
tabluar

                 Column_1              Column_2
Row1     [[1, 2], [3, 4]]      [[5, 6], [7, 8]]
Row2  [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [19]:
dataset.dropna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [22]:
dataset.head(100)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53,1,0,142,226,0,0,111,1,0.0,2,0,3,1
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3,1
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2,1
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2,1

In [23]:
dataset.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1

In [24]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [25]:
dataset.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [27]:
new=pd.DataFrame(np.random.rand(5,3),columns=['A','B','C'])
new

          A         B         C
0  0.980421  0.419444  0.833049
1  0.655003  0.199480  0.970644
2  0.347646  0.571389  0.591651
3  0.162136  0.216206  0.325705
4  0.574265  0.851230  0.583496

In [29]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [48]:
dataset.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        1
target      1
dtype: int64

In [51]:
dataset['trestbps'].fillna(dataset['trestbps'].mean(),inplace=True)

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_7892\3627110340.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['trestbps'].fillna(dataset['trestbps'].mean(),inplace=True)

In [47]:
dataset['target'].value_counts()

target
1.0    164
0.0    138
Name: count, dtype: int64

In [49]:
dataset['new_column1']=np.nan
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,new_column1
0,63,1,3,145.0,233,1,0,150,0.0,2.3,0,0,1.0,1.0,NaN
1,37,1,2,130.0,250,0,1,187,0.0,3.5,0,0,2.0,1.0,NaN
2,41,0,1,130.0,204,0,0,172,0.0,1.4,2,0,2.0,1.0,NaN
3,56,1,1,120.0,236,0,1,178,0.0,0.8,2,0,2.0,1.0,NaN
4,57,0,0,120.0,354,0,1,163,1.0,0.6,2,0,2.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140.0,241,0,1,123,1.0,0.2,1,0,3.0,0.0,NaN
299,45,1,3,110.0,264,0,1,132,0.0,1.2,1,0,3.0,0.0,NaN
300,68,1,0,144.0,193,1,1,141,0.0,3.4,1,2,3.0,0.0,NaN
301,57,1,0,130.0,131,0,1,115,1.0,1.2,1,1,3.0,0.0,NaN
302,57,0,1,130.0,236,0,0,174,0.0,0.0,1,1,2.0,0.0,NaN

In [45]:
dataset.isna().sum()

age              0
sex              0
cp               0
trestbps         0
chol             0
fbs              0
restecg          0
thalach          0
exang            0
oldpeak          0
slope            0
ca               0
thal             0
target           0
new_column1    303
dtype: int64

In [46]:
dataset=pd.read_csv('dataset.csv')

In [58]:
dataset=dataset.sort_values(by='cp',ascending=True)
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,new_column1
151,71,0,0,112.0,149,0,1,125,0.0,1.6,1,0,2.0,1.0,NaN
285,46,1,0,140.0,311,0,1,120,1.0,1.8,1,2,3.0,0.0,NaN
300,68,1,0,144.0,193,1,1,141,0.0,3.4,1,2,3.0,0.0,NaN
298,57,0,0,140.0,241,0,1,123,1.0,0.2,1,0,3.0,0.0,NaN
297,59,1,0,164.0,176,1,0,90,0.0,1.0,1,2,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,64,1,3,170.0,227,0,0,155,0.0,0.6,1,0,3.0,1.0,NaN
228,59,1,3,170.0,288,0,0,159,0.0,0.2,1,0,3.0,0.0,NaN
286,59,1,3,134.0,204,0,1,162,0.0,0.8,2,2,2.0,0.0,NaN
19,69,0,3,140.0,239,0,1,151,0.0,1.8,2,2,2.0,1.0,NaN
0,63,1,3,145.0,233,1,0,150,0.0,2.3,0,0,1.0,1.0,NaN

In [60]:
dataset.groupby('sex')['age'].mean()

sex
0    55.677083
1    53.758454
Name: age, dtype: float64

In [61]:
dataset.iloc[0:5,0:3]

     age  sex  cp
151   71    0   0
285   46    1   0
300   68    1   0
298   57    0   0
297   59    1   0

In [62]:
dataset['oldpeak']=dataset['oldpeak'].astype('int32')

In [64]:
dataset['oldpeak'].dtype

dtype('int32')

In [ ]:
#all columns unique values

for i in dataset.columns:
    print(dataset[i].unique())


# dataset['sex'].unique()

[71 46 68 57 59 43 63 58 54 61 55 35 51 52 42 47 40 65 67 56 70 44 50 62
 66 53 45 77 48 60 64 39 41 49 74 29 34 38 76 37 69]
[0 1]
[0 1 2 3]
[112.         140.         144.         164.         120.
 150.         124.         170.         114.         148.
 128.         110.         180.         122.         135.
 136.         138.         152.         100.         130.
 146.         123.         132.         104.         178.
 142.         125.         108.         115.         134.
 145.         174.         126.         165.         160.
 102.         118.         200.         117.         106.
 156.         154.         192.         105.         101.
  94.         129.         131.49006623 155.        ]
[149 311 193 241 176 354 192 247 197 187 225 239 318 203 205 207 335 327
 286 198 299 234 204 226 315 275 166 223 177 237 261 283 218 322 169 249
 200 294 302 282 230 209 259 244 208 228 264 309 212 298 304 269 260 300
 206 303 409 184 274 293 183 222 353 243 289 174 330 217 265 256 254 248
 341 407 307 219 394 233 258 255 270 236 164 325 267 288 211 326 188 216
 305 276 271 266 253 290 246 172 131 167 201 263 268 229 235 295 245 262
 250 220 195 306 308 160 157 221 342 240 232 284 319 281 210 175 242 224
 196 277 199 178 180 214 313 564 126 278 185 231 227 141 168 215 252 213
 340 360 321 273 417 257 182 186]
[0 1]
[1 0 2]
[125 120 141 123  90 163 148 171 136 144 146 160 140 161 130 138 143 117
 116 173 156 178 118 181  71 186 103 105 109 126 106 151  95 154 165 147
 132 122 162 169 185 108 159 150 166 170  88 182 168 128 124 131 111 145
 127 157 142 177 152 158  99 133 114 113 112 153  96 115 129 155 121 180
 172 202 184 179 175 164 195 174 188 192 149 167 194 139  97 187 137 134
 190]
[0.  1.  0.5]
[ 1  3  0  4  2  5  6 12]
[1 2 0]
[0 2 3 1 4]
[ 2.  3.  1.  0. nan]
[ 1.  0. nan]
[nan]

array([0, 1])

In [70]:
dataset['sex'].nunique()

2

In [76]:
# for i in dataset['age']:
#     if i>20 and i<60:
#         print(i,dataset['target'])

dataset[(dataset['age']>20) & (dataset['age']<60)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,new_column1
285,46,1,0,140.0,311,0,1,120,1.0,1,1,2,3.0,0.0,NaN
298,57,0,0,140.0,241,0,1,123,1.0,0,1,0,3.0,0.0,NaN
297,59,1,0,164.0,176,1,0,90,0.0,1,1,2,1.0,0.0,NaN
4,57,0,0,120.0,354,0,1,163,1.0,0,2,0,2.0,1.0,NaN
5,57,1,0,140.0,192,0,1,148,0.0,0,1,0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,52,1,3,118.0,186,0,0,190,0.0,0,1,0,1.0,1.0,NaN
83,52,1,3,152.0,298,1,1,178,0.0,1,1,0,3.0,1.0,NaN
299,45,1,3,110.0,264,0,1,132,0.0,1,1,0,3.0,0.0,NaN
228,59,1,3,170.0,288,0,0,159,0.0,0,1,0,3.0,0.0,NaN
286,59,1,3,134.0,204,0,1,162,0.0,0,2,2,2.0,0.0,NaN

In [78]:
for i in dataset['chol']:
    if i>200:
        print("High cholesterol:",i)
    else:
        print("Normal cholesterol:",i)

Normal cholesterol: 149
High cholesterol: 311
Normal cholesterol: 193
High cholesterol: 241
Normal cholesterol: 176
High cholesterol: 354
Normal cholesterol: 192
High cholesterol: 247
Normal cholesterol: 197
Normal cholesterol: 187
High cholesterol: 225
High cholesterol: 239
High cholesterol: 318
High cholesterol: 203
High cholesterol: 205
High cholesterol: 207
High cholesterol: 335
High cholesterol: 327
High cholesterol: 286
Normal cholesterol: 198
High cholesterol: 299
High cholesterol: 234
High cholesterol: 204
High cholesterol: 226
High cholesterol: 315
High cholesterol: 275
Normal cholesterol: 166
High cholesterol: 223
High cholesterol: 234
Normal cholesterol: 177
High cholesterol: 237
High cholesterol: 261
High cholesterol: 283
High cholesterol: 218
High cholesterol: 322
Normal cholesterol: 169
High cholesterol: 249
Normal cholesterol: 200
High cholesterol: 294
High cholesterol: 302
High cholesterol: 299
High cholesterol: 282
High cholesterol: 230
High cholesterol: 209
High cholesterol: 234
High cholesterol: 259
High cholesterol: 247
High cholesterol: 244
High cholesterol: 208
High cholesterol: 228
High cholesterol: 264
High cholesterol: 309
High cholesterol: 212
High cholesterol: 298
High cholesterol: 304
High cholesterol: 269
High cholesterol: 260
High cholesterol: 300
High cholesterol: 206
High cholesterol: 303
High cholesterol: 409
Normal cholesterol: 184
High cholesterol: 274
High cholesterol: 293
High cholesterol: 274
High cholesterol: 212
Normal cholesterol: 183
High cholesterol: 249
High cholesterol: 282
High cholesterol: 222
High cholesterol: 353
High cholesterol: 212
High cholesterol: 243
High cholesterol: 289
Normal cholesterol: 197
Normal cholesterol: 174
High cholesterol: 239
High cholesterol: 330
High cholesterol: 217
High cholesterol: 289
High cholesterol: 265
High cholesterol: 256
High cholesterol: 254
High cholesterol: 330
High cholesterol: 248
High cholesterol: 341
High cholesterol: 207
High cholesterol: 407
High cholesterol: 249
High cholesterol: 307
High cholesterol: 219
High cholesterol: 394
High cholesterol: 233
High cholesterol: 260
Normal cholesterol: 177
High cholesterol: 258
High cholesterol: 239
High cholesterol: 226
High cholesterol: 255
High cholesterol: 270
High cholesterol: 258
Normal cholesterol: 197
High cholesterol: 236
High cholesterol: 248
High cholesterol: 254
Normal cholesterol: 164
High cholesterol: 325
High cholesterol: 267
High cholesterol: 288
High cholesterol: 211
High cholesterol: 225
High cholesterol: 326
High cholesterol: 282
Normal cholesterol: 188
High cholesterol: 216
High cholesterol: 305
High cholesterol: 276
High cholesterol: 243
High cholesterol: 271
High cholesterol: 254
High cholesterol: 266
High cholesterol: 253
High cholesterol: 290
High cholesterol: 204
High cholesterol: 303
High cholesterol: 246
Normal cholesterol: 172
Normal cholesterol: 131
Normal cholesterol: 177
High cholesterol: 230
Normal cholesterol: 167
High cholesterol: 206
High cholesterol: 201
High cholesterol: 263
High cholesterol: 303
High cholesterol: 269
High cholesterol: 223
High cholesterol: 254
High cholesterol: 268
High cholesterol: 229
High cholesterol: 286
High cholesterol: 203
High cholesterol: 228
High cholesterol: 235
High cholesterol: 269
High cholesterol: 295
High cholesterol: 201
High cholesterol: 244
High cholesterol: 245
High cholesterol: 262
High cholesterol: 204
High cholesterol: 250
High cholesterol: 325
High cholesterol: 236
High cholesterol: 220
High cholesterol: 263
High cholesterol: 204
High cholesterol: 205
High cholesterol: 245
High cholesterol: 266
Normal cholesterol: 195
High cholesterol: 208
High cholesterol: 234
High cholesterol: 306
High cholesterol: 308
Normal cholesterol: 160
High cholesterol: 294
High cholesterol: 288
High cholesterol: 246
High cholesterol: 271
Normal cholesterol: 157
High cholesterol: 220
High cholesterol: 221
High cholesterol: 342
High cholesterol: 240
High cholesterol: 232
High cholesterol: 229
High cholesterol: 284
High cholesterol: 283
High cholesterol: 319
High cholesterol: 261
High cholesterol: 204
Normal cholesterol: 192
High cholesterol: 281
High cholesterol: 219
High cholesterol: 309
High cholesterol: 210
High cholesterol: 203
Normal cholesterol: 198
High cholesterol: 302
High cholesterol: 221
High cholesterol: 236
Normal cholesterol: 197
High cholesterol: 295
Normal cholesterol: 175
Normal cholesterol: 175
High cholesterol: 242
Normal cholesterol: 197
High cholesterol: 209
High cholesterol: 256
High cholesterol: 224
High cholesterol: 230
High cholesterol: 335
High cholesterol: 201
Normal cholesterol: 196
High cholesterol: 226
High cholesterol: 277
Normal cholesterol: 199
High cholesterol: 267
High cholesterol: 233
High cholesterol: 268
Normal cholesterol: 178
Normal cholesterol: 180
High cholesterol: 214
High cholesterol: 313
High cholesterol: 277
High cholesterol: 250
High cholesterol: 309
Normal cholesterol: 196
High cholesterol: 274
High cholesterol: 240
High cholesterol: 240
High cholesterol: 246
High cholesterol: 318
Normal cholesterol: 188
High cholesterol: 245
High cholesterol: 315
High cholesterol: 223
High cholesterol: 255
High cholesterol: 263
High cholesterol: 564
High cholesterol: 211
High cholesterol: 214
Normal cholesterol: 126
High cholesterol: 278
High cholesterol: 229
Normal cholesterol: 185
High cholesterol: 231
High cholesterol: 212
Normal cholesterol: 199
High cholesterol: 250
High cholesterol: 235
High cholesterol: 220
High cholesterol: 227
Normal cholesterol: 141
High cholesterol: 265
Normal cholesterol: 168
High cholesterol: 215
High cholesterol: 216
High cholesterol: 252
High cholesterol: 254
High cholesterol: 269
High cholesterol: 231
High cholesterol: 213
High cholesterol: 256
High cholesterol: 258
High cholesterol: 211
High cholesterol: 275
High cholesterol: 222
High cholesterol: 340
High cholesterol: 219
High cholesterol: 253
High cholesterol: 243
High cholesterol: 232
Normal cholesterol: 175
High cholesterol: 308
High cholesterol: 360
High cholesterol: 269
High cholesterol: 304
High cholesterol: 321
Normal cholesterol: 177
High cholesterol: 273
Normal cholesterol: 197
High cholesterol: 417
High cholesterol: 212
High cholesterol: 257
High cholesterol: 243
High cholesterol: 233
Normal cholesterol: 149
High cholesterol: 218
Normal cholesterol: 182
High cholesterol: 244
High cholesterol: 234
High cholesterol: 273
High cholesterol: 231
Normal cholesterol: 193
High cholesterol: 270
Normal cholesterol: 199
High cholesterol: 213
High cholesterol: 234
High cholesterol: 283
High cholesterol: 226
Normal cholesterol: 186
High cholesterol: 211
High cholesterol: 298
High cholesterol: 282
High cholesterol: 240
High cholesterol: 264
High cholesterol: 227
High cholesterol: 288
High cholesterol: 204
High cholesterol: 239
High cholesterol: 233

In [77]:
for i in dataset['chol']:
    if i>200:
        print("High cholesterol:",i)
    else:
        print("Normal cholesterol:",i)

Normal cholesterol: 149
High cholesterol: 311
Normal cholesterol: 193
High cholesterol: 241
Normal cholesterol: 176
High cholesterol: 354
Normal cholesterol: 192
High cholesterol: 247
Normal cholesterol: 197
Normal cholesterol: 187
High cholesterol: 225
High cholesterol: 239
High cholesterol: 318
High cholesterol: 203
High cholesterol: 205
High cholesterol: 207
High cholesterol: 335
High cholesterol: 327
High cholesterol: 286
Normal cholesterol: 198
High cholesterol: 299
High cholesterol: 234
High cholesterol: 204
High cholesterol: 226
High cholesterol: 315
High cholesterol: 275
Normal cholesterol: 166
High cholesterol: 223
High cholesterol: 234
Normal cholesterol: 177
High cholesterol: 237
High cholesterol: 261
High cholesterol: 283
High cholesterol: 218
High cholesterol: 322
Normal cholesterol: 169
High cholesterol: 249
Normal cholesterol: 200
High cholesterol: 294
High cholesterol: 302
High cholesterol: 299
High cholesterol: 282
High cholesterol: 230
High cholesterol: 209
High cholesterol: 234
High cholesterol: 259
High cholesterol: 247
High cholesterol: 244
High cholesterol: 208
High cholesterol: 228
High cholesterol: 264
High cholesterol: 309
High cholesterol: 212
High cholesterol: 298
High cholesterol: 304
High cholesterol: 269
High cholesterol: 260
High cholesterol: 300
High cholesterol: 206
High cholesterol: 303
High cholesterol: 409
Normal cholesterol: 184
High cholesterol: 274
High cholesterol: 293
High cholesterol: 274
High cholesterol: 212
Normal cholesterol: 183
High cholesterol: 249
High cholesterol: 282
High cholesterol: 222
High cholesterol: 353
High cholesterol: 212
High cholesterol: 243
High cholesterol: 289
Normal cholesterol: 197
Normal cholesterol: 174
High cholesterol: 239
High cholesterol: 330
High cholesterol: 217
High cholesterol: 289
High cholesterol: 265
High cholesterol: 256
High cholesterol: 254
High cholesterol: 330
High cholesterol: 248
High cholesterol: 341
High cholesterol: 207
High cholesterol: 407
High cholesterol: 249
High cholesterol: 307
High cholesterol: 219
High cholesterol: 394
High cholesterol: 233
High cholesterol: 260
Normal cholesterol: 177
High cholesterol: 258
High cholesterol: 239
High cholesterol: 226
High cholesterol: 255
High cholesterol: 270
High cholesterol: 258
Normal cholesterol: 197
High cholesterol: 236
High cholesterol: 248
High cholesterol: 254
Normal cholesterol: 164
High cholesterol: 325
High cholesterol: 267
High cholesterol: 288
High cholesterol: 211
High cholesterol: 225
High cholesterol: 326
High cholesterol: 282
Normal cholesterol: 188
High cholesterol: 216
High cholesterol: 305
High cholesterol: 276
High cholesterol: 243
High cholesterol: 271
High cholesterol: 254
High cholesterol: 266
High cholesterol: 253
High cholesterol: 290
High cholesterol: 204
High cholesterol: 303
High cholesterol: 246
Normal cholesterol: 172
Normal cholesterol: 131
Normal cholesterol: 177
High cholesterol: 230
Normal cholesterol: 167
High cholesterol: 206
High cholesterol: 201
High cholesterol: 263
High cholesterol: 303
High cholesterol: 269
High cholesterol: 223
High cholesterol: 254
High cholesterol: 268
High cholesterol: 229
High cholesterol: 286
High cholesterol: 203
High cholesterol: 228
High cholesterol: 235
High cholesterol: 269
High cholesterol: 295
High cholesterol: 201
High cholesterol: 244
High cholesterol: 245
High cholesterol: 262
High cholesterol: 204
High cholesterol: 250
High cholesterol: 325
High cholesterol: 236
High cholesterol: 220
High cholesterol: 263
High cholesterol: 204
High cholesterol: 205
High cholesterol: 245
High cholesterol: 266
Normal cholesterol: 195
High cholesterol: 208
High cholesterol: 234
High cholesterol: 306
High cholesterol: 308
Normal cholesterol: 160
High cholesterol: 294
High cholesterol: 288
High cholesterol: 246
High cholesterol: 271
Normal cholesterol: 157
High cholesterol: 220
High cholesterol: 221
High cholesterol: 342
High cholesterol: 240
High cholesterol: 232
High cholesterol: 229
High cholesterol: 284
High cholesterol: 283
High cholesterol: 319
High cholesterol: 261
High cholesterol: 204
Normal cholesterol: 192
High cholesterol: 281
High cholesterol: 219
High cholesterol: 309
High cholesterol: 210
High cholesterol: 203
Normal cholesterol: 198
High cholesterol: 302
High cholesterol: 221
High cholesterol: 236
Normal cholesterol: 197
High cholesterol: 295
Normal cholesterol: 175
Normal cholesterol: 175
High cholesterol: 242
Normal cholesterol: 197
High cholesterol: 209
High cholesterol: 256
High cholesterol: 224
High cholesterol: 230
High cholesterol: 335
High cholesterol: 201
Normal cholesterol: 196
High cholesterol: 226
High cholesterol: 277
Normal cholesterol: 199
High cholesterol: 267
High cholesterol: 233
High cholesterol: 268
Normal cholesterol: 178
Normal cholesterol: 180
High cholesterol: 214
High cholesterol: 313
High cholesterol: 277
High cholesterol: 250
High cholesterol: 309
Normal cholesterol: 196
High cholesterol: 274
High cholesterol: 240
High cholesterol: 240
High cholesterol: 246
High cholesterol: 318
Normal cholesterol: 188
High cholesterol: 245
High cholesterol: 315
High cholesterol: 223
High cholesterol: 255
High cholesterol: 263
High cholesterol: 564
High cholesterol: 211
High cholesterol: 214
Normal cholesterol: 126
High cholesterol: 278
High cholesterol: 229
Normal cholesterol: 185
High cholesterol: 231
High cholesterol: 212
Normal cholesterol: 199
High cholesterol: 250
High cholesterol: 235
High cholesterol: 220
High cholesterol: 227
Normal cholesterol: 141
High cholesterol: 265
Normal cholesterol: 168
High cholesterol: 215
High cholesterol: 216
High cholesterol: 252
High cholesterol: 254
High cholesterol: 269
High cholesterol: 231
High cholesterol: 213
High cholesterol: 256
High cholesterol: 258
High cholesterol: 211
High cholesterol: 275
High cholesterol: 222
High cholesterol: 340
High cholesterol: 219
High cholesterol: 253
High cholesterol: 243
High cholesterol: 232
Normal cholesterol: 175
High cholesterol: 308
High cholesterol: 360
High cholesterol: 269
High cholesterol: 304
High cholesterol: 321
Normal cholesterol: 177
High cholesterol: 273
Normal cholesterol: 197
High cholesterol: 417
High cholesterol: 212
High cholesterol: 257
High cholesterol: 243
High cholesterol: 233
Normal cholesterol: 149
High cholesterol: 218
Normal cholesterol: 182
High cholesterol: 244
High cholesterol: 234
High cholesterol: 273
High cholesterol: 231
Normal cholesterol: 193
High cholesterol: 270
Normal cholesterol: 199
High cholesterol: 213
High cholesterol: 234
High cholesterol: 283
High cholesterol: 226
Normal cholesterol: 186
High cholesterol: 211
High cholesterol: 298
High cholesterol: 282
High cholesterol: 240
High cholesterol: 264
High cholesterol: 227
High cholesterol: 288
High cholesterol: 204
High cholesterol: 239
High cholesterol: 233

In [ ]:
dataset['cholesterol_status']=dataset['chol'].apply(lambda x: "High cholesterol" if x>200 else "Low cholesterol")
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,new_column1,cholesterol_status
151,71,0,0,112.0,149,0,1,125,0.0,1,1,0,2.0,1.0,NaN,Normal cholesterol
285,46,1,0,140.0,311,0,1,120,1.0,1,1,2,3.0,0.0,NaN,High cholesterol
300,68,1,0,144.0,193,1,1,141,0.0,3,1,2,3.0,0.0,NaN,Normal cholesterol
298,57,0,0,140.0,241,0,1,123,1.0,0,1,0,3.0,0.0,NaN,High cholesterol
297,59,1,0,164.0,176,1,0,90,0.0,1,1,2,1.0,0.0,NaN,Normal cholesterol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,64,1,3,170.0,227,0,0,155,0.0,0,1,0,3.0,1.0,NaN,High cholesterol
228,59,1,3,170.0,288,0,0,159,0.0,0,1,0,3.0,0.0,NaN,High cholesterol
286,59,1,3,134.0,204,0,1,162,0.0,0,2,2,2.0,0.0,NaN,High cholesterol
19,69,0,3,140.0,239,0,1,151,0.0,1,2,2,2.0,1.0,NaN,High cholesterol
0,63,1,3,145.0,233,1,0,150,0.0,2,0,0,1.0,1.0,NaN,High cholesterol

In [ ]:
new_dataset=dataset.copy()
new_dataset

AttributeError: 'DataFrame' object has no attribute 'deepcopy'

In [83]:
dataset.duplicated()

151    False
285    False
300    False
298    False
297    False
       ...
152    False
228    False
286    False
19     False
0      False
Length: 303, dtype: bool

In [85]:
dataset.reset_index(drop=True,inplace=True)

In [86]:
dataset["new_column1"]=replace()

NameError: name 'replace' is not defined