In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("transactions.csv")
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,06-26-2015,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,05-26-2015,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,06-01-2015,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,06-05-2015,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,12-17-2015,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,09-18-2015,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,10-02-2015,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,05-03-2015,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,10-23-2015,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,12-14-2015,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

In [5]:
total_sales=df["t_amt"].sum()
total_sales

np.float64(5110820.54)

In [6]:
df["t_date"]=pd.to_datetime(df["t_date"])

In [7]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

In [8]:
df["month"]=df["t_date"].dt.month

In [9]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details,month
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit,6
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit,5
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit,6
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit,6
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit,12
...,...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit,9
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit,10
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash,5
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit,10
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit,12

## TASK 2

In [10]:
highest_sales=df.groupby(df["t_date"].dt.month)['t_amt'].sum().idxmax()
highest_sales

np.int32(3)

## TASK 3

In [11]:
avg_trans=df.groupby("cust_id")["t_amt"].mean()
avg_trans

cust_id
4000000    127.444000
4000001    108.945556
4000002     56.165000
4000003    123.670000
4000004    168.135000
              ...
4009995     65.018571
4009996    104.515000
4009997    121.547500
4009998    110.950000
4009999     85.252500
Name: t_amt, Length: 9926, dtype: float64

## TASK 4

In [12]:
# to find the trends of sales across different months

tsales_month=df.groupby("month")["t_amt"].sum()
tsales_month

# tsales_month=df[df.groupby("month")["cust_id"]]
# tsales_month

month
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

## TASK 5

In [13]:
max_trans=df["t_amt"].max()
max_trans

200.0

## TASK 6

In [14]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details,month
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit,6
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit,5
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit,6
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit,6
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit,12
...,...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit,9
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit,10
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash,5
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit,10
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit,12

In [15]:
max_Service=df.groupby("services")["t_amt"].sum().idxmax()
max_Service

'Outdoor Recreation'

## TASK 7

In [16]:
max_product=df.groupby("products_used")["t_amt"].sum().idxmax()
max_product

'Yoga & Pilates'

## TASK 8

## TASK 12

In [17]:
totalcnt=df.groupby("cust_id")["services"].value_counts()
totalcnt

cust_id  services
4000000  Outdoor Recreation        2
         Games                     1
         Indoor Games              1
         Winter Sports             1
4000001  Racquet Sports            2
                                  ..
4009999  Water Sports              3
         Outdoor Recreation        2
         Outdoor Play Equipment    1
         Racquet Sports            1
         Team Sports               1
Name: count, Length: 39790, dtype: int64

## TASK 13

In [18]:
buyer=df["cust_id"].count()
buyer

np.int64(50000)

In [19]:
unq=df["cust_id"].nunique()
unq

9926

In [20]:
diff=buyer-unq
diff
perc=diff/buyer*100
perc

np.float64(80.148)

## TASK 14

In [21]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details,month
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit,6
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit,5
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit,6
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit,6
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit,12
...,...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit,9
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit,10
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash,5
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit,10
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit,12

In [22]:
max_serv=df.groupby("services")["t_amt"].sum().idxmax()
max_serv
# max_serv.max().idmax()

'Outdoor Recreation'

## TASK 15

In [23]:
max_serv1=df.groupby("services")["t_amt"].count().idxmax()
max_serv1

'Outdoor Recreation'

## TASK 16

In [24]:

#For each service, which product type is purchased most frequently? 
# freq_prod=df.groupby("services")["products_used"].value_counts()
# freq_prod
freq_prod=df.groupby("services")["products_used"].agg(lambda x:x.value_counts().idxmax())
freq_prod

services
Air Sports                                Parachutes
Combat Sports                                 Boxing
Dancing                                  Ballet Bars
Exercise & Fitness        Cardio Machine Accessories
Games                                        Mahjong
Gymnastics                             Balance Beams
Indoor Games                                Foosball
Jumping                                  Trampolines
Outdoor Play Equipment                    Swing Sets
Outdoor Recreation                        Lawn Games
Puzzles                               Jigsaw Puzzles
Racquet Sports                             Badminton
Team Sports                                   Hockey
Water Sports                            Bodyboarding
Winter Sports                   Cross-Country Skiing
Name: products_used, dtype: object

In [25]:
freq_prod.idxmax()

'Jumping'

## TASK 17

In [26]:
avg_trans=df.groupby("products_used")["t_amt"].mean()
avg_trans

products_used
Abdominal Equipment    105.362798
Air Hockey             103.775478
Air Suits              101.421832
Archery                 97.345564
Badminton              108.441138
                          ...
Wetsuits               102.042775
Whitewater Rafting     102.877744
Windsurfing            104.161453
Wrestling               97.895364
Yoga & Pilates         107.668784
Name: t_amt, Length: 125, dtype: float64

## TASK 18

In [27]:
avg_sale=df["t_amt"].mean()
specific_serv=df.loc[df["t_amt"]>avg_sale,"services"]
specific_serv

1        Exercise & Fitness
3                Gymnastics
5        Outdoor Recreation
9                   Jumping
10       Outdoor Recreation
                ...
49992          Water Sports
49994    Outdoor Recreation
49996                 Games
49998            Gymnastics
49999           Team Sports
Name: services, Length: 24899, dtype: object

## TASK 19

In [28]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details,month
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit,6
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit,5
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit,6
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit,6
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit,12
...,...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit,9
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit,10
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash,5
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit,10
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit,12

In [29]:
total_sales=df.groupby("state")["t_amt"].sum()
total_sales.idxmax()

'California'

## TASK 20

In [30]:
city_maxcount=df.groupby("city")["cust_id"].count().idxmax()
city_maxcount

'Pasadena'

## TASK 21

In [31]:
df.groupby("state")["t_amt"].mean()

state
Alabama                 102.487049
Arizona                 102.172241
California              102.652182
Colorado                101.537415
Connecticut              99.982108
District of Columbia    103.800334
Florida                 103.136567
Georgia                 102.330675
Hawaii                  101.536667
Idaho                    98.969538
Illinois                100.166315
Indiana                 100.712664
Iowa                    103.100727
Kansas                  101.436926
Kentucky                104.130392
Louisiana               103.466335
Maryland                100.506913
Massachusetts           104.541571
Michigan                101.547777
Minnesota               103.465157
Mississippi             101.214926
Missouri                100.969040
Nebraska                101.955690
Nevada                  105.434718
New Jersey              103.438005
New York                100.259452
North Carolina          103.033172
Ohio                    101.350817
Oklahoma                104.995771
Oregon                  102.438143
Pennsylvania            102.776034
South Carolina          103.540065
Tennessee                99.265804
Texas                   101.379891
Utah                    104.507560
Virginia                104.976206
Washington              101.401603
Wisconsin               101.953159
Name: t_amt, dtype: float64

## TASK 22

In [32]:

#Are certain services more popular in specific states
# df.groupby(["services","state"])["cust_id"].count().unstack().idxmax(axis=1) #    ##doubt???

# import statistics as st
# st.mode(df.groupby("services")["state"].count().values.idxmax())

import statistics as st
popular=df.groupby("state")["services"].apply(st.mode)
st.mode(popular)

'Outdoor Recreation'

## TASK 23

In [33]:
df.loc[df['services']=='Outdoor Recreation'].groupby('state')['t_amt'].sum().idxmax()

'California'

## TASK 24

In [34]:
cal=df.loc[df["state"]=="California"].groupby("state")["t_amt"].sum()
cal=int(cal)
cal

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_37416\2098776313.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  cal=int(cal)

702346

In [35]:
texas=df.loc[df["state"]=="Texas"].groupby("state")["t_amt"].sum()
texas=int(texas)
texas

C:\Users\N.SAI VAIBHAV\AppData\Local\Temp\ipykernel_37416\2094565746.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  texas=int(texas)

541267

In [36]:
avgg=(cal+texas)/2
avgg

621806.5

## TASK 25

In [39]:
df['t_date']=pd.to_datetime(df['t_date'],dayfirst=True,errors='coerce')
quaterly=df.groupby(df['t_date'].dt.quarter)['t_amt'].sum()
quaterly.idxmax()

np.int32(3)

In [40]:
monthly_sale=df.groupby(df['t_date'].dt.month)['t_amt'].sum()
monthly_sale

t_date
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

In [41]:
transactions=df.groupby(df['t_date'].dt.month)['t_amt'].count()
transactions

t_date
1     4268
2     3834
3     4360
4     4175
5     4205
6     4171
7     4252
8     4250
9     4160
10    4181
11    3994
12    4150
Name: t_amt, dtype: int64

In [42]:
df["month"] = df["t_date"].dt.month
def get_season(m):
    if m in [12,1,2]: return "Winter"
    elif m in [3,4,5]: return "Spring"
    elif m in [6,7,8]: return "Summer"
    else: return "Fall"

df["season"] = df["month"].apply(get_season)
pivot = pd.crosstab(df["services"], df["season"])
pivot.idxmax(axis=1)

services
Air Sports                  Fall
Combat Sports             Winter
Dancing                   Summer
Exercise & Fitness        Spring
Games                     Summer
Gymnastics                Summer
Indoor Games                Fall
Jumping                   Summer
Outdoor Play Equipment    Spring
Outdoor Recreation        Spring
Puzzles                   Spring
Racquet Sports            Summer
Team Sports               Spring
Water Sports              Summer
Winter Sports             Spring
dtype: object

In [43]:
credit_count=df.loc[df['t_details']=='credit']
credit_count['t_details'].count()

np.int64(43151)

In [44]:
#What is the total revenue generated from credit transactions?
credit_revenue=credit_count['t_amt'].sum()
credit_revenue

np.float64(4923134.93)

In [45]:
df['t_details'].unique()

array(['credit', 'cash'], dtype=object)

In [46]:
cutoff = df["t_amt"].quantile(0.75)
high = df[df["t_amt"] >= cutoff]
high.groupby("state")["t_amt"].sum().sort_values(ascending=False)

state
California              306298.42
Texas                   230455.90
Florida                 121560.46
Oregon                   79133.17
Ohio                     78869.72
Colorado                 78488.36
Washington               78109.70
Tennessee                74908.87
Virginia                 66245.30
Massachusetts            63150.99
Arizona                  59795.79
Missouri                 58575.71
Illinois                 58155.11
New Jersey               57024.10
Wisconsin                52091.42
Alabama                  48982.95
Nevada                   43379.00
Michigan                 43139.65
South Carolina           40963.04
Kansas                   40598.90
New York                 40209.84
Kentucky                 40102.33
Nebraska                 39242.90
Pennsylvania             38605.97
Minnesota                38470.82
Connecticut              37682.61
Utah                     37598.01
Georgia                  36761.80
North Carolina           35633.84
District of Columbia     22025.18
Iowa                     20408.58
Louisiana                20228.46
Oklahoma                 19846.19
Hawaii                   19526.57
Mississippi              18532.72
Maryland                 18156.37
Idaho                    18011.06
Indiana                  17755.07
Name: t_amt, dtype: float64

In [47]:
df.groupby("services")["t_amt"].sum().sort_values(ascending=False)

services
Outdoor Recreation        846678.64
Exercise & Fitness        766463.87
Team Sports               617461.38
Water Sports              531815.97
Games                     374932.70
Gymnastics                327225.34
Winter Sports             321973.56
Outdoor Play Equipment    294728.28
Indoor Games              288506.04
Jumping                   205842.67
Racquet Sports            166976.06
Combat Sports             164730.67
Air Sports                 99316.90
Puzzles                    61564.75
Dancing                    42603.71
Name: t_amt, dtype: float64

In [48]:
summary = df.groupby("services")["t_amt"].agg(["sum", "mean", "count"])
summary.sort_values("sum", ascending=False)

                              sum        mean  count
services
Outdoor Recreation      846678.64  100.999480   8383
Exercise & Fitness      766463.87  103.660247   7394
Team Sports             617461.38  102.738998   6010
Water Sports            531815.97  101.899975   5219
Games                   374932.70  102.272968   3666
Gymnastics              327225.34  102.385901   3196
Winter Sports           321973.56  101.217718   3181
Outdoor Play Equipment  294728.28  101.281196   2910
Indoor Games            288506.04  103.074684   2799
Jumping                 205842.67  102.155171   2015
Racquet Sports          166976.06  103.647461   1611
Combat Sports           164730.67  101.061761   1630
Air Sports               99316.90  103.455104    960
Puzzles                  61564.75  100.595997    612
Dancing                  42603.71  102.907512    414

In [49]:
summary.sort_values("sum")

                              sum        mean  count
services
Dancing                  42603.71  102.907512    414
Puzzles                  61564.75  100.595997    612
Air Sports               99316.90  103.455104    960
Combat Sports           164730.67  101.061761   1630
Racquet Sports          166976.06  103.647461   1611
Jumping                 205842.67  102.155171   2015
Indoor Games            288506.04  103.074684   2799
Outdoor Play Equipment  294728.28  101.281196   2910
Winter Sports           321973.56  101.217718   3181
Gymnastics              327225.34  102.385901   3196
Games                   374932.70  102.272968   3666
Water Sports            531815.97  101.899975   5219
Team Sports             617461.38  102.738998   6010
Exercise & Fitness      766463.87  103.660247   7394
Outdoor Recreation      846678.64  100.999480   8383